language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"
  - "node"
  - "iojs"
before_script:
  - gem update --system
  - gem install sass
  - 'npm install -g grunt-cli'
  - 'grunt'
